In [2]:
import numpy as np


In [11]:
a = np.array([[[1, 2, 3, 4, 5, 6], [6, 7, 8, 9, 6, 2], [456, 789, 32,1 ,5, 8]], [[1, 2, 3, 4, 5, 6], [6, 7, 8, 9, 6, 2], [456, 789, 32,1 ,5, 8]], [[1, 2, 3, 4, 5, 6], [6, 7, 8, 9, 6, 2], [456, 789, 32,1 ,5, 8]]])
# a = np.array([[[1, 2, 3], [2,3,4], [5,6,7]], [[1, 2, 3], [2,3,4], [5,6,7]], [[1, 2, 3], [2,3,4], [5,6,7]]])
print(a)
print(a.shape)
ar = np.random.randint(1, 20, size=(5,5))
print(ar)


[[[  1   2   3   4   5   6]
  [  6   7   8   9   6   2]
  [456 789  32   1   5   8]]

 [[  1   2   3   4   5   6]
  [  6   7   8   9   6   2]
  [456 789  32   1   5   8]]

 [[  1   2   3   4   5   6]
  [  6   7   8   9   6   2]
  [456 789  32   1   5   8]]]
(3, 3, 6)
[[14 17  4  5 12]
 [14 14  3  4 15]
 [15 13 18 17  3]
 [14  1  1  9 12]
 [13  6 15 11  5]]


In [27]:
ar[:, :] = 78
print(ar)

[[78 78 78 78 78]
 [78 78 78 78 78]
 [78 78 78 78 78]
 [78 78 78 78 78]
 [78 78 78 78 78]]


In [31]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)
np.fill_diagonal(arr, 1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  1  7  8]
 [ 9 10  1 12]
 [13 14 15  1]]


In [7]:
arr = np.arange(1, 37).reshape(6, 6)
print(arr)
arr[2:5, 1:4]



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [23]:
arr = np.random.randint(1, 20, size=(5,5))
print(arr)
rows, columns = arr.shape
print(rows, columns)
print(arr[0])
print(arr[1:, 0])
print(arr[1:, 4])
print(arr[-1, 1:-1])
border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print(border_elements)

[[19  7 10 12  4]
 [ 1 16 13 11 16]
 [10 18 14  6 11]
 [ 3 14 16 18  5]
 [12  3 17  9 18]]
5 5
[19  7 10 12  4]
[ 1 10  3 12]
[16 11  5 18]
[ 3 17  9]
[19  7 10 12  4 12  3 17  9 18  1 10  3 16 11  5]


In [26]:
arr = np.random.randint(1, 20, size=(3,4))
arr1 = np.random.randint(1, 20, size=(3,4))
print(arr)
print(arr1)
print(arr+arr1)
print(arr-arr1)
print(arr*arr1)


[[ 3  3  4  1]
 [13 11 12 16]
 [11 12  9 15]]
[[ 9  3  2 19]
 [18  6 12  8]
 [ 2  2 16 12]]
[[12  6  6 20]
 [31 17 24 24]
 [13 14 25 27]]
[[ -6   0   2 -18]
 [ -5   5   0   8]
 [  9  10  -7   3]]
[[ 27   9   8  19]
 [234  66 144 128]
 [ 22  24 144 180]]


In [30]:
# arr1 = np.random.randint(1, 20, size=(3,4))
arr = np.arange(1, 17).reshape(4, 4)
print(arr)
np.sum(arr, axis = 1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([10, 26, 42, 58])

In [33]:
arr = np.random.randint(1, 50, size=(5, 5))
print(arr)
print(np.sum(arr)/25)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

[[ 4 30 34 18 13]
 [13 17 25 11 44]
 [36 22 29 21 25]
 [36 17 11 39 13]
 [41 12 37 20 22]]
23.6
23.6
22.0
10.848041297856495
117.68000000000002


In [36]:
arr1 = np.arange(1, 10).reshape(3,3)
print(arr1)

print(np.mean(arr1))

print(np.std(arr1))

print((arr1-np.mean(arr1))/(np.std(arr1)))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
2.581988897471611
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
