In [2]:
import numpy as np


In [ ]:
a = np.array([[[1, 2, 3, 4, 5, 6], [6, 7, 8, 9, 6, 2], [456, 789, 32,1 ,5, 8]], [[1, 2, 3, 4, 5, 6], [6, 7, 8, 9, 6, 2], [456, 789, 32,1 ,5, 8]], [[1, 2, 3, 4, 5, 6], [6, 7, 8, 9, 6, 2], [456, 789, 32,1 ,5, 8]]])
# a = np.array([[[1, 2, 3], [2,3,4], [5,6,7]], [[1, 2, 3], [2,3,4], [5,6,7]], [[1, 2, 3], [2,3,4], [5,6,7]]])
print(a)
print(a.shape)
ar = np.random.randint(1, 20, size=(5,5))
ar = np.array([1, 2, 3, 4, 5])
ar = []
ar = [1, 2, 3, 4, 5]
print(ar)


[[[  1   2   3   4   5   6]
  [  6   7   8   9   6   2]
  [456 789  32   1   5   8]]

 [[  1   2   3   4   5   6]
  [  6   7   8   9   6   2]
  [456 789  32   1   5   8]]

 [[  1   2   3   4   5   6]
  [  6   7   8   9   6   2]
  [456 789  32   1   5   8]]]
(3, 3, 6)
[1 2 3 4]


In [27]:
ar[:, :] = 78
print(ar)

[[78 78 78 78 78]
 [78 78 78 78 78]
 [78 78 78 78 78]
 [78 78 78 78 78]
 [78 78 78 78 78]]


In [31]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)
np.fill_diagonal(arr, 1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  1  7  8]
 [ 9 10  1 12]
 [13 14 15  1]]


In [7]:
arr = np.arange(1, 37).reshape(6, 6)
print(arr)
arr[2:5, 1:4]



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [23]:
arr = np.random.randint(1, 20, size=(5,5))
print(arr)
rows, columns = arr.shape
print(rows, columns)
print(arr[0])
print(arr[1:, 0])
print(arr[1:, 4])
print(arr[-1, 1:-1])
border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print(border_elements)

[[19  7 10 12  4]
 [ 1 16 13 11 16]
 [10 18 14  6 11]
 [ 3 14 16 18  5]
 [12  3 17  9 18]]
5 5
[19  7 10 12  4]
[ 1 10  3 12]
[16 11  5 18]
[ 3 17  9]
[19  7 10 12  4 12  3 17  9 18  1 10  3 16 11  5]


In [26]:
arr = np.random.randint(1, 20, size=(3,4))
arr1 = np.random.randint(1, 20, size=(3,4))
print(arr)
print(arr1)
print(arr+arr1)
print(arr-arr1)
print(arr*arr1)


[[ 3  3  4  1]
 [13 11 12 16]
 [11 12  9 15]]
[[ 9  3  2 19]
 [18  6 12  8]
 [ 2  2 16 12]]
[[12  6  6 20]
 [31 17 24 24]
 [13 14 25 27]]
[[ -6   0   2 -18]
 [ -5   5   0   8]
 [  9  10  -7   3]]
[[ 27   9   8  19]
 [234  66 144 128]
 [ 22  24 144 180]]


In [30]:
# arr1 = np.random.randint(1, 20, size=(3,4))
arr = np.arange(1, 17).reshape(4, 4)
print(arr)
np.sum(arr, axis = 1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([10, 26, 42, 58])

In [33]:
arr = np.random.randint(1, 50, size=(5, 5))
print(arr)
print(np.sum(arr)/25)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

[[ 4 30 34 18 13]
 [13 17 25 11 44]
 [36 22 29 21 25]
 [36 17 11 39 13]
 [41 12 37 20 22]]
23.6
23.6
22.0
10.848041297856495
117.68000000000002


In [36]:
arr1 = np.arange(1, 10).reshape(3,3)
print(arr1)

print(np.mean(arr1))

print(np.std(arr1))

print((arr1-np.mean(arr1))/(np.std(arr1)))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
2.581988897471611
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [4]:
arr = np.random.randint(11, 30, size=(3,3))
print(arr)
oneArr = np.array([1, 2, 3])
arr + oneArr

[[18 17 11]
 [25 14 20]
 [21 20 23]]


array([[19, 19, 14],
       [26, 16, 23],
       [22, 22, 26]])

In [12]:
arr = np.random.randint(11, 30, size=(3,3))
print(arr)
oneArr = np.array([1, 2, 3])
# np.subtract(arr, oneArr)  
result = arr - (oneArr[:, np.newaxis])
# print(oneArr[:, np.newaxis])
print(result)

[[16 13 21]
 [22 27 18]
 [25 22 14]]
[[15 12 20]
 [20 25 16]
 [22 19 11]]


In [ ]:
## Linear Algebra

In [15]:
arr = np.random.randint(1, 10, size= (3,3))
print(arr)
np.linalg.det(arr)
print(np.linalg.inv(arr))
print(np.linalg.eigvals(arr))


[[4 4 7]
 [5 4 3]
 [3 8 1]]
[[-0.15151515  0.39393939 -0.12121212]
 [ 0.03030303 -0.12878788  0.17424242]
 [ 0.21212121 -0.15151515 -0.03030303]]
[12.95229236+0.j        -1.97614618+2.5072081j -1.97614618-2.5072081j]


In [19]:
arr = np.random.randint(1, 3, size= (3,2))
print(arr)
arr1 = np.random.randint(1, 3, size= (2,3))
print(arr1)
np.linalg.matmul(arr, arr1)


[[2 1]
 [1 1]
 [1 1]]
[[1 2 2]
 [1 2 1]]


array([[3, 6, 5],
       [2, 4, 3],
       [2, 4, 3]])

In [20]:
arr = np.arange(1, 10).reshape(3,3)
print(arr)
print(arr.reshape(1, 9))
print(arr.reshape(9,1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [22]:
arr = np.random.randint(1, 25, size=(5,5))
print(arr)
print(arr.flatten().shape)


[[ 7 24  6 10 14]
 [ 7 22 18 12 11]
 [ 4 12 23 14 10]
 [19 11 18 10  3]
 [13 11 10  5  9]]
(25,)


Fancy Indexing

In [57]:
arr = np.random.randint(1, 25, size=(5,5))
print(arr)
print(arr[0:1, 0:1], arr[0:1, 4:5], arr[4:5, 0:1], arr[4:5, 4:5])
# print(arr[-1, -1])
corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]
print(corners)


[[15  2 12  9  3]
 [ 4 19 12 17 21]
 [14 15 14 22 21]
 [18  3 19 13  1]
 [19  5  8  7 10]]
[[15]] [[3]] [[19]] [[10]]
[15  3 19 10]


In [66]:
arr = np.random.randint(1, 25, size=(4,4))
print(arr)

# arr[arr>10] = 10
mask = np.where(arr > 10, True , False)
print(arr[mask])

[[ 6  9  7  6]
 [ 4 17 21  9]
 [ 3  7 22 20]
 [ 8  1 13 19]]
[17 21 22 20 13 19]


In [7]:

arr = np.array([{"name": "alice", "age": 25, "weight": 55}, {"name": "bob", "age": 30, "weight": 70}, {"name": "charlie", "age": 35, "weight": 80}])
print(arr)
data_type = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'i4')])
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print(data)
np.sort(data, order='age')

[{'name': 'alice', 'age': 25, 'weight': 55}
 {'name': 'bob', 'age': 30, 'weight': 70}
 {'name': 'charlie', 'age': 35, 'weight': 80}]
[('Alice', 25, 55) ('Bob', 30, 85) ('Charlie', 20, 65)]


array([('Charlie', 20, 65), ('Alice', 25, 55), ('Bob', 30, 85)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<i4')])

In [35]:
dtype = np.dtype([('x', 'i4'), ('y', 'i4')])
array = np.array([(1, 2), (3, 4), (5, 6)], dtype=dtype)
# print(array)
# print(array['x'][:, np.newaxis])
print(array[:, np.newaxis])
distances = np.sqrt((array['x'][:, np.newaxis] - array['x'])**2 + (array['y'][:, np.newaxis] - array['y'])**2)
# print(array['x'])
print(distances)

# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)


[[(1, 2)]
 [(3, 4)]
 [(5, 6)]]
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]
Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [58]:
arr = np.random.randint(1, 24, size=(4,4))
print(arr)
masked = np.where(arr==5, True, False)
asdf = np.logical_xor(arr>10, arr<20)
print(asdf)
# print(masked)
np.sum(arr[masked])
# un_masked = arr[arr>10]
# np.sum(un_masked)

[[ 9 10  9 18]
 [13 10 18  9]
 [11  1  4  6]
 [22 18 22  8]]
[[ True  True  True False]
 [False  True False  True]
 [False  True  True  True]
 [ True False  True  True]]


np.int64(0)

In [65]:

arr = np.random.randint(1, 18, size=(3,3))
d_mask = np.ma.masked_array(arr, mask=np.eye(3, dtype=float))
print(d_mask)

[[-- 6 6]
 [10 -- 3]
 [8 14 --]]


In [78]:
array = np.random.randint(4, 5, size=(3, 3))
# print(np.eye(4, dtype=bool))
masked_array = np.ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)
mean = masked_array.mean()
# np.mean(masked_array) 
np.fill_diagonal(masked_array, mean)
print(masked_array)

Original array:
[[4 4 4]
 [4 4 4]
 [4 4 4]]
Masked array:
[[-- 4 4]
 [4 -- 4]
 [4 4 --]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
